=== AlibekMaks/lmsMaven/src/main/resources/mime-map-dic_1_1.dtd
<!-- mime-map-dic DTD Version1.1 -->
<!-- ALL CONTENTS COPYRIGHT 2005, OOP-Research Corporation. -->
<!-- All rights reserved. -->
<!-- Any questions and comments are welcome to -->
<!-- tech@oop-research.com -->

<!ELEMENT mime-map-dic (default-mime, mime-mapping*, mime2ext*)>

<!ELEMENT default-mime (#PCDATA)>

<!ELEMENT mime-mapping (extension, mime-type)>

<!ELEMENT mime2ext (mime-type, extension)>

<!ELEMENT extension (#PCDATA)>

<!ELEMENT mime-type (#PCDATA)>

=== AlibekMaks/lmsMaven/src/main/resources/mime.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE mime-map-dic PUBLIC "-//OOP-Research Corporation//DTD MimeMapDic 1.1//EN" "http://www.bentofw.com/dtd/mime-map-dic_1_1.dtd">

<mime-map-dic>

    <default-mime>
       application/octet-stream
    </default-mime>

<!--
    <default-mime>
       text/plain
    </default-mime>
-->

    <mime-mapping>
        <extension>
            djv
        </extension>
        <mime-type>
		image/djvu            
        </mime-type>
    </mime-mapping>

    <mime-mapping>
        <extension>
            djvu
        </extension>
        <mime-type>
		image/djvu            
        </mime-type>
    </mime-mapping>

    <mime-mapping>
        <extension>
            txt
        </extension>
        <mime-type>
            text/plain
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            html
        </extension>
        <mime-type>
            text/html
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            htm
        </extension>
        <mime-type>
            text/html
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            png
        </extension>
        <mime-type>
            image/png
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            gif
        </extension>
        <mime-type>
            image/gif
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            jpg
        </extension>
        <mime-type>
            image/jpeg
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            jpe
        </extension>
        <mime-type>
            image/jpeg
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            jpeg
        </extension>
        <mime-type>
            image/jpeg
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            java
        </extension>
        <mime-type>
            text/plain
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            body
        </extension>
        <mime-type>
            text/html
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            rtx
        </extension>
        <mime-type>
            text/richtext
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            tsv
        </extension>
        <mime-type>
            text/tab-separated-values
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            etx
        </extension>
        <mime-type>
            text/x-setext
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            ps
        </extension>
        <mime-type>
            application/x-postscript
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            class
        </extension>
        <mime-type>
            application/java
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            csh
        </extension>
        <mime-type>
            application/x-csh
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            sh
        </extension>
        <mime-type>
            application/x-sh
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            tcl
        </extension>
        <mime-type>
            application/x-tcl
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            tex
        </extension>
        <mime-type>
            application/x-tex
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            texinfo
        </extension>
        <mime-type>
            application/x-texinfo
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            texi
        </extension>
        <mime-type>
            application/x-texinfo
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            t
        </extension>
        <mime-type>
            application/x-troff
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            tr
        </extension>
        <mime-type>
            application/x-troff
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            roff
        </extension>
        <mime-type>
            application/x-troff
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            man
        </extension>
        <mime-type>
            application/x-troff-man
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            me
        </extension>
        <mime-type>
            application/x-troff-me
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            ms
        </extension>
        <mime-type>
            application/x-wais-source
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            src
        </extension>
        <mime-type>
            application/x-wais-source
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            zip
        </extension>
        <mime-type>
            application/zip
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            bcpio
        </extension>
        <mime-type>
            application/x-bcpio
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            cpio
        </extension>
        <mime-type>
            application/x-cpio
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            gtar
        </extension>
        <mime-type>
            application/x-gtar
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            shar
        </extension>
        <mime-type>
            application/x-shar
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            sv4cpio
        </extension>
        <mime-type>
            application/x-sv4cpio
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            sv4crc
        </extension>
        <mime-type>
            application/x-sv4crc
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            tar
        </extension>
        <mime-type>
            application/x-tar
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            ustar
        </extension>
        <mime-type>
            application/x-ustar
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            dvi
        </extension>
        <mime-type>
            application/x-dvi
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            hdf
        </extension>
        <mime-type>
            application/x-hdf
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            latex
        </extension>
        <mime-type>
            application/x-latex
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            bin
        </extension>
        <mime-type>
            application/octet-stream
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            oda
        </extension>
        <mime-type>
            application/oda
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            pdf
        </extension>
        <mime-type>
            application/pdf
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            ps
        </extension>
        <mime-type>
            application/postscript
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            eps
        </extension>
        <mime-type>
            application/postscript
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            ai
        </extension>
        <mime-type>
            application/postscript
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            rtf
        </extension>
        <mime-type>
            application/rtf
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            nc
        </extension>
        <mime-type>
            application/x-netcdf
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            cdf
        </extension>
        <mime-type>
            application/x-netcdf
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            cer
        </extension>
        <mime-type>
            application/x-x509-ca-cert
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            exe
        </extension>
        <mime-type>
            application/octet-stream
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            gz
        </extension>
        <mime-type>
            application/x-gzip
        </mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>
            Z
        </extension>
        <mime-type>
            application/x-compress
